project_id = "cuabhynevjfnswaciunm"

[functions.upload-audio]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
import_map = "./import_map.json"

[functions.transcribe-audio.environment]
OPENAI_API_KEY = "env.OPENAI_API_KEY"

[functions.analyze-conversation]
verify_jwt = false

[functions.check-api-key]
verify_jwt = false

[functions.check-api-key.environment]
OPENAI_API_KEY = "env.OPENAI_API_KEY"