project_id = "cuabhynevjfnswaciunm"

[functions.upload-audio]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-conversation]
verify_jwt = true

[functions.check-api-key-v2]
verify_jwt = false

[functions.test-api-key]
verify_jwt = false